arr = [
  { url: 'https://play.google.com/store/apps/details?id=com.netflix.mediaclient',
    appId: 'com.netflix.mediaclient',
    title: 'Netflix',
    summary: 'A Netflix é o principal serviço de transmissão online de séries e filmes.',
    developer: 'Netflix, Inc.',
    developerId: 'Netflix,+Inc.',
    icon: '//lh3.googleusercontent.com/jcbqFma-5e91cY9MlEasA-fvCRJK493MxphrqbBd8oS74FtYg00IXeOAn0ahsLprxIA=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.forshared',
    appId: 'com.forshared',
    title: '4shared',
    summary: 'Acesse, gerencie e compartilhe seus arquivos do 4shared com outras pessoas.',
    developer: 'New IT Solutions',
    developerId: 'New+IT+Solutions',
    icon: '//lh3.googleusercontent.com/783dtPGKTOsQiO-IZNjM6FE4LS7yFTGzd1GE0shSIOiv9goF0efEaqFctQ3fvwbmvcK5=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.ss.android.article.topbuzzvideo.general',
    appId: 'com.ss.android.article.topbuzzvideo.general',
    title: 'BuzzVídeo - Vídeos Engraçados, GIFs e TV Shows',
    summary: 'Receba Vídeos e GIFs mais populares e engraçados da Internet com o BuzzVídeo',
    developer: 'TopBuzz Global',
    developerId: 'TopBuzz+Global',
    icon: '//lh3.googleusercontent.com/_Gr-U2zAU4FZ1P1J_Ehkara2bIStLtaLuE29u6TEwYb7PQF18GsMpQxYIfZQYpuybCM=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.google.android.play.games',
    appId: 'com.google.android.play.games',
    title: 'Google Play Games',
    summary: 'Jogos incríveis para você acumular conquistas e as maiores pontuações.',
    developer: 'Google LLC',
    developerId: '5700313618786177705',
    icon: '//lh3.googleusercontent.com/UFJL7ni5i_F8V9Em0yymU4_x8uWhpKqDiA13Zo3ybgPJa48ujJjNfHLbvKr-3_MXzjLa=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.globo.globotv',
    appId: 'com.globo.globotv',
    title: 'Globo Play',
    summary: 'Novelas, séries, humor, realities, jornalismo e esportes quando e onde quiser.',
    developer: 'Globo Comunicação e Participações S.A.',
    developerId: 'Globo+Comunica%C3%A7%C3%A3o+e+Participa%C3%A7%C3%B5es+S.A.',
    icon: '//lh3.googleusercontent.com/YmObYSH0zSinNwSKEjabHE2KWMax6ldBcfCngn97bEwxnTmiADqW97jBkA2tcghZoGU=w340',
    score: 3,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.alertmovies.beta',
    appId: 'com.alertmovies.beta',
    title: 'Series e Filmes HD Gratuitos',
    summary: 'Fique atualizado sempre com o seu Alerta de Filmes Online',
    developer: 'RGRJ Apps',
    developerId: 'RGRJ+Apps',
    icon: '//lh3.googleusercontent.com/139P9uZ3C28faxGf1Ihi7QbNVuDGq2bwj8WDrYaNKtzYTZSD-r2Hx_sstocsT2w_qhfu=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.creative.sandbox.number.drawning.coloring',
    appId: 'com.creative.sandbox.number.drawning.coloring',
    title: 'No.Draw - Cor por Páginas de Número',
    summary: 'Jogo de coloração mais favorito por adultos e crianças! Download gratuito agora!',
    developer: 'Creative APPS',
    developerId: 'Creative+APPS',
    icon: '//lh3.googleusercontent.com/eTKhgnUwGkqdWQ6ICW7j1MM3MUfVMnDYH8zJJaZOcdEKMhWsIWtL-rUjXq5Wd5667TU=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.bitstrips.imoji',
    appId: 'com.bitstrips.imoji',
    title: 'Bitmoji',
    summary: 'Transforme-se num emoji personalizado para usar em mensagens de chat!',
    developer: 'Bitstrips',
    developerId: 'Bitstrips',
    icon: '//lh3.googleusercontent.com/VgApWOljUS_6OKp80OV--HjqsECnd95s0gpzslLJ277G-tYZH6X6ZF8KnQy_fjvvChA=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.globo.gshow.app',
    appId: 'com.globo.gshow.app',
    title: 'Gshow',
    summary: 'O conteúdo de Entretenimento da TV Globo em vídeos, fotos e notícias exclusivas.',
    developer: 'Globo Comunicação e Participações S.A.',
    developerId: 'Globo+Comunica%C3%A7%C3%A3o+e+Participa%C3%A7%C3%B5es+S.A.',
    icon: '//lh3.googleusercontent.com/hUVVyt7vgvaaDyi_egCtUKnsHHD1DalyRsERbecJxnnXbjeScuLVScboN1y3RAZ0jnD3=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=tv.online53',
    appId: 'tv.online53',
    title: 'Assistir tv no celular (Public channels only)',
    summary: 'Com o aplicativo você vai assistir canais públicos de TV no seu celular.',
    developer: 'HostDogApp',
    developerId: 'HostDogApp',
    icon: '//lh3.googleusercontent.com/Be2-OQL11NO1F3vZ-9MvlsBow5OKNNdDHlPJvJeP0jFd2GbctwiTj2YxFyaSUqf1wx4=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=sandbox.art.sandbox',
    appId: 'sandbox.art.sandbox',
    title: 'Sandbox - Cor por Páginas de Número',
    summary: 'Colorir por Número de Páginas para colorir',
    developer: 'Alexey Grigorkin',
    developerId: 'Alexey+Grigorkin',
    icon: '//lh3.googleusercontent.com/R4VALCvpHDAhS6e95z9q_gBRad2N57ZjnhS89Cs9L4c7F2JquwqHNw_VMQ7hfj_YoKE=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=br.com.telecineplay.android',
    appId: 'br.com.telecineplay.android',
    title: 'Telecine Play - Filmes Online',
    summary: 'O Telecine Play é o melhor app de filmes online.',
    developer: 'Telecine Programação de Filmes Ltda.',
    developerId: 'Telecine+Programa%C3%A7%C3%A3o+de+Filmes+Ltda.',
    icon: '//lh3.googleusercontent.com/d7fCSsJPdpP7q-YjQwnBtUIBwmCbcJ_dt-FsEkRlvwhPnr6TpZjBlZajfPyAzX7vgXs=w340',
    score: 3,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.digidust.elokence.akinator.freemium',
    appId: 'com.digidust.elokence.akinator.freemium',
    title: 'Akinator',
    summary: 'O Akinator pode ler sua mente e dizer o personagem no qual você está pensando!',
    developer: 'Elokence',
    developerId: '9041369024808341661',
    icon: 'https://lh4.ggpht.com/ZqeqVpm0nPVT5tHmnT5xreOWnDghhQWxnn07uHf4J86zW3LC1_KG2C55gycrbZv7dMA=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=br.com.sky.selfcare',
    appId: 'br.com.sky.selfcare',
    title: 'Minha SKY',
    summary: 'Baixe o App Minha SKY. Diversão para toda sua família!',
    developer: 'SKY Brasil',
    developerId: 'SKY+Brasil',
    icon: '//lh3.googleusercontent.com/l5bkA7p3LVJClfv5N5ooud9qooNE57e0A_8BxceJq88-fFCJy8nV8xTtnu80ix_H51c=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.google.android.apps.youtube.kids',
    appId: 'com.google.android.apps.youtube.kids',
    title: 'YouTube Kids',
    summary: 'Melhor video app para crianças',
    developer: 'Google LLC',
    developerId: '5700313618786177705',
    icon: '//lh3.googleusercontent.com/k_HSvNKlleJNrzuL3OqDuXFm3Es8d77UQtiZvPqLg8lera9Xj99GRkDwWaJGMz8nkb1B=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.movile.playkids',
    appId: 'com.movile.playkids',
    title: 'PlayKids - Vídeos, livros e jogos educativos',
    summary: 'Aprenda com desenhos, livros, jogos e atividades que as crianças amam.',
    developer: 'PlayKids Inc',
    developerId: '8508730787410367067',
    icon: '//lh3.googleusercontent.com/hMHXo1scvzJfTNYzNcXkh-swj2UbpBMcdQ4Vaceo2NwHT_nlJpW9I2T8b0eTYMX-iQ=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.mobillle.assistir',
    appId: 'com.mobillle.assistir',
    title: 'TV Play - Assistir TV Online',
    summary: 'TV Play - Assista TV online quando e onde quiser',
    developer: 'TVPlay',
    developerId: 'TVPlay',
    icon: '//lh3.googleusercontent.com/leREMgHrLwidLR57xR-p8LeLJS13u8kyX9zuocXS6nfjV4OoPfdViOH6ktm-mimeERs=w340',
    score: 3,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.smart.color.phone.emoji',
    appId: 'com.smart.color.phone.emoji',
    title: 'Telefone com Emojis',
    summary: '🎨Personalize seu telefone para um estilo emoji😍',
    developer: 'Cute Emoji Studio',
    developerId: '6481465927745266711',
    icon: '//lh3.googleusercontent.com/LEoL5rKL78pW5anm8l8fgtAA-YRbV6axbhLvlbtTCmO319tDpus4AUPKrHxqMwTH-Q=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.ismaker.android.simsimi',
    appId: 'com.ismaker.android.simsimi',
    title: 'SimSimi',
    summary: 'A qualquer hora em qualquer lugar SimSimi falar com você!',
    developer: 'SimSimi Inc.',
    developerId: 'SimSimi+Inc.',
    icon: 'https://lh4.ggpht.com/lNHAV_rUG6uAUjcvCLax7m20i2KZIbdtvBdxjDmXI7Q3dOHKHGzq3oYa_xMHclc7JBI=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=funmakermod.newgunsmods',
    appId: 'funmakermod.newgunsmods',
    title: 'New GUNS mod',
    summary: 'Todas as novas armas mods para Minecraft pe! A maioria maior coleção!',
    developer: 'funmakermod',
    developerId: 'funmakermod',
    icon: '//lh3.googleusercontent.com/F_z1RVb9vvQN5ws195J2X1BY7H42bLPwkzzZfWF0bDLghO9COtGFm3LhSC2rS9lXmtYY=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.outfit7.talkingtom',
    appId: 'com.outfit7.talkingtom',
    title: 'Talking Tom',
    summary: 'Tenha diversão instantânea com esse bichinho virtual. Fale, e o Tom vai repetir.',
    developer: 'Outfit7',
    developerId: '5950758182267281572',
    icon: '//lh3.googleusercontent.com/feIHJk4hh3Q1Kopm6rsaDnXgeejWvIRmW1ZmFMg6faBQ4eMpCilCitwc4Mpm8xHor3A=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.tvseries.gratis',
    appId: 'com.tvseries.gratis',
    title: 'tv séries free',
    summary: 'Tenha sua programação de tv séries free',
    developer: 'Apps em Alta',
    developerId: 'Apps+em+Alta',
    icon: '//lh3.googleusercontent.com/pqRf1i0rsJYP0633Hn764hhIXdgtU9SSNN_gq2gt6sbfLulFP7_--Hvfl-Ey3C0dnA=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=br.com.sbt.app',
    appId: 'br.com.sbt.app',
    title: 'TV SBT',
    summary: 'Aplicativo do SBT, aqui você encontra os vídeos dos seus programas favoritos!',
    developer: 'TV SBT Canal 4 São Paulo S/A',
    developerId: 'TV+SBT+Canal+4+S%C3%A3o+Paulo+S/A',
    icon: '//lh6.ggpht.com/FP-vGJG4o9ygXU7gLXuaBJQMfu5kTa2YZSwblfsrJRJS0Vqosckc2GDzHD1NQ5zjdA=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=tv.twitch.android.app',
    appId: 'tv.twitch.android.app',
    title: 'Twitch',
    summary: 'Assista e converse sobre os seus jogos, jogadores e eventos preferidos.',
    developer: 'Twitch Interactive, Inc.',
    developerId: 'Twitch+Interactive,+Inc.',
    icon: '//lh3.googleusercontent.com/Ti7DQ5NH92V-_uuOiTbMOMwAjVXzl2rubjygxQp3KGutzuRHnjYvpCtfWJybeDYh4g=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.ss.android.ugc.boomlite',
    appId: 'com.ss.android.ugc.boomlite',
    title: 'Hypstar Lite',
    summary: 'Comunidade de vídeos curtos engraçados',
    developer: 'BYTEMOD PTE.LTD.',
    developerId: 'BYTEMOD+PTE.LTD.',
    icon: '//lh3.googleusercontent.com/IxX1sm7EMnqQYRflFjvWrs9Zjx1QH6FSm5HQBstlWZz4zem8ak5A9tOZux5aw_7vxD8=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.discovery.kids.pt',
    appId: 'com.discovery.kids.pt',
    title: 'Discovery K!ds Play!',
    summary: 'No Discovery K!ds Play seus filhos, divertem e assistem de suas séries favoritas',
    developer: 'Discovery Communications Limited',
    developerId: 'Discovery+Communications+Limited',
    icon: '//lh3.googleusercontent.com/S2P6e1VXYtG2f7cdTGO1HkLxVimkYKjh6dwIj5QB9LmpRF5_sHMBig4RW2yeMu0nDlNr=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=br.com.net.netapp',
    appId: 'br.com.net.netapp',
    title: 'Minha NET',
    summary: 'Minha NET e a programação da NET HDTV em poucos cliques, na palma da mão.',
    developer: 'NET e Claro',
    developerId: 'NET+e+Claro',
    icon: '//lh3.googleusercontent.com/9rQDOsa7tbt095lcq-0X0ETW8BUzIUZD9ZdjViWmd83uo3x5WFoDD85gIjsQl-ZiwBZS=w340',
    score: 3,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.microsoft.xboxone.smartglass',
    appId: 'com.microsoft.xboxone.smartglass',
    title: 'Xbox',
    summary: 'Xbox',
    developer: 'Microsoft Corporation',
    developerId: '6720847872553662727',
    icon: '//lh3.googleusercontent.com/YqlXGn_KbC5zxxEDr12vsYWjcMpZokEmGZ76opYh4VmRwa2FCP6fHYzFcad5-xj4C677=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.fakecallgame',
    appId: 'com.fakecallgame',
    title: 'Chamada Falsa',
    summary: 'Divirta-se com uma brincadeira falsa.',
    developer: 'GameAndro',
    developerId: 'GameAndro',
    icon: '//lh3.googleusercontent.com/8DP4fxuXp9ilwUdQsNX7ofu4qzDdbgiTjBKidBQUM9BagPwfHvzytY7jjahzoJbmRRM=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.renato.garcia.dot',
    appId: 'com.renato.garcia.dot',
    title: 'Renato Garcia',
    summary: 'MOSTRO MEU DIA A DIA COM MINHA MOTO E MEU CARRO, CUJO SÃO MEUS SONHOS REALIZADOS',
    developer: 'Generated',
    developerId: 'Generated',
    icon: '//lh3.googleusercontent.com/CoSQfG4YNGeUbLA3kSFpPB1HbqcLiWT-CAu7_phQEqDOjPX79NTal-PT1JQxUlS57w=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.outfit7.talkinggingerfree',
    appId: 'com.outfit7.talkinggingerfree',
    title: 'Talking Ginger',
    summary: 'O pequeno Talking Ginger precisa da sua ajuda!',
    developer: 'Outfit7',
    developerId: '5950758182267281572',
    icon: '//lh3.googleusercontent.com/oUreGSlB0ARGUQDFMW4x_vwze46AnLpExDuxQHykYmmNcJU1KZS7n0jtH_zzMknNYw=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.number.draw.dot.to.dot.coloring',
    appId: 'com.number.draw.dot.to.dot.coloring',
    title: 'Dot to Dot to Coloring',
    summary: 'Ponto para ponto por número e coloração livro em um! Dobrar o jogo dobro da diversão!',
    developer: 'Color Apps For Free',
    developerId: 'Color+Apps+For+Free',
    icon: '//lh3.googleusercontent.com/_DFg3pBEMuqFDn-YW6BzJh69BSyDE-ozMZqJZq49FOhi5N8T5u-XQ_unISXWpXnZFA=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.bandai.dbscgapp',
    appId: 'com.bandai.dbscgapp',
    title: 'Dragon Ball Super Card Game Tutorial',
    summary: 'Jogar a versão digital do Dragon Ball Super Card Game e aprender as regras!',
    developer: 'BANDAI CO.,LTD.',
    developerId: 'BANDAI+CO.,LTD.',
    icon: '//lh3.googleusercontent.com/kCYMlc_eay50JHD_xBLUFGc-ATKfwHPvk7p8kXYQ4OeqX-nLF1aa-o64lY6ZXcY9CzE=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.boomboomapps.melivideos',
    appId: 'com.boomboomapps.melivideos',
    title: 'Meri Videos',
    summary: 'Meri Mast Vídeos',
    developer: 'Boom Boom Applications',
    developerId: 'Boom+Boom+Applications',
    icon: '//lh3.googleusercontent.com/CJC9bj65ebosoofBppAKOgb0vupA95Y4pxwmQBGcsVh7YLQ8dEfZ-iFQUQVtSF1Gbu2E=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.vysionapps.face28',
    appId: 'com.vysionapps.face28',
    title: 'Face Changer Video',
    summary: 'Enfrente 28 - Vídeo face Changer com filtros selfie. Urdidura rosto e trocar rosto.',
    developer: 'VysionApps',
    developerId: 'VysionApps',
    icon: '//lh3.googleusercontent.com/drpKVAuUD_-vaIfCYmigS8pXEZFmG5O3xbNH_Rq9MJcXSZq61snjLvy7u1t5LBLq6A=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.fungamesforfree.colorfy',
    appId: 'com.fungamesforfree.colorfy',
    title: 'Colorfy: Livro de Colorir para Adultos - Grátis',
    summary: 'O novo livro de colorir para adultos para Android! GRÁTIS',
    developer: 'Fun Games For Free',
    developerId: '8186084684070471579',
    icon: '//lh3.googleusercontent.com/tLZ2qvqXlprr12fHpGaMjyILH3Z-Asp_tliPIwYU-Z73aetSZ87mbWmAmjgg71IKHiY=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.viaapps.videos.bhojpuri2',
    appId: 'com.viaapps.videos.bhojpuri2',
    title: 'Hot Bhojpuri Video songs',
    summary: 'filmes completos Bhojpuri, Bhojpuri Vídeo Canção 2017, 2017 novas canções Bhojpuri',
    developer: 'as23apps',
    developerId: 'as23apps',
    icon: '//lh3.googleusercontent.com/NVlVwVU8wrUtp9p1DylRgnXu9hiuDQQeoQn17qLNTvJlNqmath7GdrZGenr63bs6Bps=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.codescheatforgtafree.sa',
    appId: 'com.codescheatforgtafree.sa',
    title: 'Code Cheat for GTA San Andreas',
    summary: 'Gta San Andraeas batota código de graça, ajuda de dívida Torne-se Manly em Los Santos!',
    developer: 'Theft Developer',
    developerId: 'Theft+Developer',
    icon: '//lh3.googleusercontent.com/vC68Yn_jrXue7sQ7YeR5eTDmlIoV1OgewKwvWTQVqvK3Nq7v0xk38QryBxRSYVvjdA=w340',
    score: 3,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.outfit7.talkingben',
    appId: 'com.outfit7.talkingben',
    title: 'Talking Ben',
    summary: 'Conheça o Ben, o melhor "amigo" do Talking Tom!',
    developer: 'Outfit7',
    developerId: '5950758182267281572',
    icon: '//lh3.googleusercontent.com/WYt4kjUSjDpNFkAV3LWFbCdE52-leUyNFbRSj2GcHsaQq-5d9hqsPRs83qvmo1SDBTai=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.outfit7.tomlovesangelafree',
    appId: 'com.outfit7.tomlovesangelafree',
    title: 'Tom ama Angela',
    summary: 'O romance está no ar para Tom e Angela!',
    developer: 'Outfit7',
    developerId: '5950758182267281572',
    icon: '//lh3.googleusercontent.com/BZxtXRcemdJ1w8SrqcVNE_I8l0npAZuIkk6crhh7QM4x3ZERtY-QgKQIbygxa67Itw=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=br.com.globosat.android.sportvplay',
    appId: 'br.com.globosat.android.sportvplay',
    title: 'SporTV Play',
    summary: 'Tudo sobre o mundo dos esportes no SporTV ao vivo e quando quiser!',
    developer: 'Globosat',
    developerId: 'Globosat',
    icon: '//lh3.googleusercontent.com/0xOIgGQ33mg1fiEQPJqC0gvOMihv-tHwpq9fQ91ZSvAbPumFHkZ79ZfANHcaxTxmsK0=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.devnuevos.buscamusica',
    appId: 'com.devnuevos.buscamusica',
    title: 'Pesquisar música',
    summary: 'Pesquise suas músicas e baixe-as facilmente.',
    developer: 'Dev Carlos',
    developerId: 'Dev+Carlos',
    icon: '//lh3.googleusercontent.com/wa76dNyghmmtGyOfZso8V7qnydYy_VozVBavk4GKChhtweLktIiY0IrqdlPqg7WEsQ=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=tv.no.celular',
    appId: 'tv.no.celular',
    title: 'TV no Celular',
    summary: 'Simples Rápido e prático para assistir tv ao vivo.',
    developer: 'Gadi Sistemas de Sites',
    developerId: '6913544155665101760',
    icon: '//lh3.googleusercontent.com/YoHB9rLGClKKVLku0gIZyXV3z7Bu1oPl7mePSfH0Ab-fyGZRgyVzVghTwkU9rlUlFhc=w340',
    score: 3,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=br.com.globosat.gloobplay',
    appId: 'br.com.globosat.gloobplay',
    title: 'Gloob Play',
    summary: 'O Mundo Gloob em suas mãos para você levar para qualquer lugar!',
    developer: 'Globosat',
    developerId: 'Globosat',
    icon: '//lh3.googleusercontent.com/vKTJboHYK20rcMgdlcwz5C3Dp7ckgA-Or9nX1nq3LchIXMahUHUSP_ys435wg7ozDY4=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=br.com.netcombo.now',
    appId: 'br.com.netcombo.now',
    title: 'NOW  NET e Claro',
    summary: 'Clientes NET, Claro hdtv, Claro Pós e Controle curtem filmes e séries',
    developer: 'NET e Claro',
    developerId: 'NET+e+Claro',
    icon: '//lh3.googleusercontent.com/Co3dInd-Wnb6JcH9s4By1qeexmObkjE5SaOfZqGvO9uMvo_WStNekwS8S-Zn23Z0bw=w340',
    score: 2,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.comodescobrirsenhawifi.prankapp',
    appId: 'com.comodescobrirsenhawifi.prankapp',
    title: 'Descobrir Senha Wifi Prank',
    summary: 'Descobrir senha wifi Prank é um novo aplicativo wifi gratuito',
    developer: 'AppSenhaWi',
    developerId: 'AppSenhaWi',
    icon: '//lh3.googleusercontent.com/ai4ywyFk6QWTKeOpY4TtBDrWrSr3mzS7mriNQgxUIaFImcflvguaB45Cjx6NoX5iOw8=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=s.player',
    appId: 's.player',
    title: 'Super TV Player',
    summary: 'Super TV Player Aplicativo',
    developer: 'js webdesigner',
    developerId: 'js+webdesigner',
    icon: '//lh3.googleusercontent.com/eW1otRTvRdTHah55NHZWbxnHjNiKb8VSh-Kk8_XL70xBulEdckxeis008RHnpdcCJwxD=w340',
    score: 3,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=tv.aovivo.gratis',
    appId: 'tv.aovivo.gratis',
    title: 'Tv ao vivo Grátis',
    summary: 'Assista os principais canais de TVs disponíveis na palma de sua mão.',
    developer: 'Gadi Sistemas de Sites',
    developerId: '6913544155665101760',
    icon: '//lh3.googleusercontent.com/J5WUFFOn_aSt7R_dUzGbluxgDnMqwbFlaJswNQWzNwuq6izZLDU834mJSaWePnXuq1Q=w340',
    score: 3,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.playpublic.radio',
    appId: 'com.playpublic.radio',
    title: 'Assistir TV Online',
    summary: 'Assista seus canais favoritos com o GoPlayer',
    developer: 'playersports',
    developerId: 'playersports',
    icon: '//lh3.googleusercontent.com/r4csU0wu8uETRYIiOxQf2EFNrkOwdBoNq1ycWH7AWoCDihiqtXhxUTqsrJBBqs9Wi9w=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=f.industries.fakemessages',
    appId: 'f.industries.fakemessages',
    title: 'Fake Chat Conversations',
    summary: 'Diverte-te com os teus amigos criando Conversas Falsas!',
    developer: 'FocApp',
    developerId: '5378114606146012544',
    icon: '//lh3.googleusercontent.com/TXOkbIXhY3__c3yESmo3ZsovE725GQK1opSydXBVZJBdoycrWefhkR3UyjdMKXubD289=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.outfit7.talkingtom2free',
    appId: 'com.outfit7.talkingtom2free',
    title: 'Talking Tom 2',
    summary: 'Talking Tom, o gato falante original, está de volta e melhor do que nunca.',
    developer: 'Outfit7',
    developerId: '5950758182267281572',
    icon: '//lh3.googleusercontent.com/Ef1eTh77Pb9mLD87UCoWlKgjZlCti7_i5IWIU8tvHkEZ0uKI3jgzprk5rOLJbyQyHiGE=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=vg.modern.formcpe',
    appId: 'vg.modern.formcpe',
    title: 'Modern Houses and Furniture for MCPE',
    summary: 'Download gratuito mods casas modernas para MCPE! Instale agora!',
    developer: 'Trivia Studio',
    developerId: 'Trivia+Studio',
    icon: '//lh3.googleusercontent.com/_mE8ew-ZHjyEbcxfQXKAxL7UC_4EkhBK1dPDfkImU0319uF6vneKH_0Jc3ZTBgIoeAw=w340',
    score: 3,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.ismartcreations.xraybodyscanner',
    appId: 'com.ismartcreations.xraybodyscanner',
    title: 'XRay Scanner Prank',
    summary: 'Digitalize qualquer parte do corpo e dar um X-Ray Scanner usando XRay Prank app.',
    developer: 'Creative Softech',
    developerId: '7508588377644881295',
    icon: '//lh3.googleusercontent.com/gosE2uDa0azZTOALnYaLiX50Xs1KKOz0GB9tgX2sk4NKPfO9VKq7c_WFrBhS1PbwJt4=w340',
    score: 3,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.outfit7.talkingpierrefree',
    appId: 'com.outfit7.talkingpierrefree',
    title: 'Talking Pierre',
    summary: 'Você está pronto para uma performance incrível na guitarra?',
    developer: 'Outfit7',
    developerId: '5950758182267281572',
    icon: '//lh3.googleusercontent.com/sa3rXt6LaaESIj66Jlecv58IBZI-4mWHZceSl5d1xhySqDxKNEDeOQlZyhjsPwfgFnk=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=elementare.indiretasprontas',
    appId: 'elementare.indiretasprontas',
    title: 'Indiretas para Status',
    summary: 'Diversas opções de indiretas para Status do WhatsApp e compartilhamento.',
    developer: 'Elementare Tecnologia',
    developerId: '5519781793734030457',
    icon: '//lh3.googleusercontent.com/0zQhr1tutAU1muZCteuzqOowcGTzxB4Rot1dZm1Un1L-SAIfk1tSblyEav9iGoisdkw=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.nickappintl.android.nickelodeon',
    appId: 'com.nickappintl.android.nickelodeon',
    title: 'Nickelodeon Play',
    summary: 'O app da Nick traz mais diversão, mais rápido e o melhor conteúdo da Nickelodeon',
    developer: 'Nickelodeon',
    developerId: 'Nickelodeon',
    icon: '//lh3.googleusercontent.com/qe03VD80oPb_AWt6icnAVxEhmAb1F5FwEwRCJDsjsftO4T9UsuoVUr8JEmbUeg8yWgU=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.ElfizMedia.DubStepMusicMakerRM',
    appId: 'com.ElfizMedia.DubStepMusicMakerRM',
    title: 'DubStep Music Maker – Rhythm Machine & Beat Maker',
    summary: 'Crie músicas e vire o rei do dubstep com um incrível app de compor com beatpad.',
    developer: 'Elfiz Media',
    developerId: 'Elfiz+Media',
    icon: '//lh3.googleusercontent.com/lQQqzQ_KJKI5YIUGDXtrNeWtGyjzKFXS9s5nGLHfsWmn-gn3dzbFmsCclgrs8KuiwSU=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.detector.lie.game.prank',
    appId: 'com.detector.lie.game.prank',
    title: 'Truque do teste de detecção de mentira Prank',
    summary: '(Aplicativo Prank) Lie Detector simula testar a verdade.',
    developer: 'Eijoy Entertainment',
    developerId: '8524665212274194051',
    icon: '//lh3.googleusercontent.com/ThZ9u4cX1a5LhX0kWzXRAVbZorUkcQONvU6NE1XqFls9vnxERjKuY1UxMQDi5KadjBM=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=madlipz.eigenuity.com',
    appId: 'madlipz.eigenuity.com',
    title: 'MadLipz',
    summary: 'MadLipz permite que você faça voz instantâneo sobre paródias!',
    developer: 'Eigenuity Inc.',
    developerId: 'Eigenuity+Inc.',
    icon: '//lh3.googleusercontent.com/70j0DgE3po-gbOrjf0D7DcoyJ25c3xrJkG5I6RFqZuFB38vXdcu7jRxs6lHkvH7sztI=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.acessevip.tvoqpassa',
    appId: 'com.acessevip.tvoqpassa',
    title: 'Online Play',
    summary: 'Play de TV Online',
    developer: 'Andre Horiqueri',
    developerId: 'Andre+Horiqueri',
    icon: '//lh3.googleusercontent.com/ALSbrhADZ44JpkdvjH1AJcIT_EdRJZPMWYUW5WrwowRDTmOvy-3oA6XW2D3aIEe37g=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.STS.Nail.Salon.Manicure.Game',
    appId: 'com.STS.Nail.Salon.Manicure.Game',
    title: 'Unhas Decoradas - Salão de Manicure Jogo',
    summary: 'Mostrem sua criatividade no salão de unhas virtual. O melhor jogo para meninas!',
    developer: 'Smart Tools Studio',
    developerId: 'Smart+Tools+Studio',
    icon: '//lh3.googleusercontent.com/niNK1dyNj3TZxbwstVRnyvU2TDu1f7sE_qo-V9cB94b6lF4u3Lsi3Sx27JCzp6Ch0Mc=w340',
    score: 3,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=in.downloader.www.downloaders',
    appId: 'in.downloader.www.downloaders',
    title: 'Smart Tube(b)',
    summary: 'Tubo inteligente (b)',
    developer: 'Sravan maurya',
    developerId: 'Sravan+maurya',
    icon: '//lh3.googleusercontent.com/7wqR9wTwXKLHJNUI3pgqfGnml5yyACbSTHp85POPmNoV5faqJ-oBMfzlFiM5QHvejg4=w340',
    score: 3,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=modernhouses.minecrafthome.mansionminecraft',
    appId: 'modernhouses.minecrafthome.mansionminecraft',
    title: 'Modern Houses for Minecraft  ★',
    summary: 'Modern creations for Minecraft PE',
    developer: 'FimoNikiApps',
    developerId: 'FimoNikiApps',
    icon: '//lh3.googleusercontent.com/5bj_aSEqdpdKcDKfC8Q1T8RJyuiqKxs1aVhBufQirFU0ZUoIO1E2625sIzUrUQmsrXzQ=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.globo.muuandroidv1',
    appId: 'com.globo.muuandroidv1',
    title: 'Globosat Play: Programas de TV',
    summary: 'Assista aos seus canais preferidos ao vivo e reveja o que passou na TV!',
    developer: 'Globosat',
    developerId: 'Globosat',
    icon: '//lh3.googleusercontent.com/N-JyvZjqZhnvydN9Q7Hbzwh6aAQmvnAmf1TjlvqHpCnvVl5zwSU7jlJH0uLFpNiRFw=w340',
    score: 3,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=brazil.mksat.tv.free.channels',
    appId: 'brazil.mksat.tv.free.channels',
    title: 'Brazil TV MK Sat Free',
    summary: 'Assista Brasil TV satélite Informação Online Gratuito.',
    developer: 'Sat Media TV',
    developerId: 'Sat+Media+TV',
    icon: '//lh3.googleusercontent.com/BpW9Xp2k8s-OII3q_SHMMPf8Vzy2iC-IezFIfq6IadyN3WyAIMvOQes05sTaG7TMmqcE=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.mozabra.planetadasgemeasnew',
    appId: 'com.mozabra.planetadasgemeasnew',
    title: 'Planeta das Gêmeas Novo',
    summary: 'Assista a todos os vídeos do canal Planeta das Gêmeas',
    developer: 'mozabra',
    developerId: 'mozabra',
    icon: '//lh3.googleusercontent.com/bpkYEYuSVkezAWsCq7eN2dAnqolCluFontKUDQH3JQjLbJHUp7zLqc_0Dgsjy73iWZ1E=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=carinhadeanjovideos.rfm.com.carinhadeanjovideos',
    appId: 'carinhadeanjovideos.rfm.com.carinhadeanjovideos',
    title: 'Carinha de Anjo Videos',
    summary: 'Assista vídeos e a episódios da novela Carinha de Anjo',
    developer: 'RODRIGO FRANCISCO DE MATTOS',
    developerId: 'RODRIGO+FRANCISCO+DE+MATTOS',
    icon: '//lh3.googleusercontent.com/3P8j6MvKRCPypbRZKpFAJWBg4PGx7r13TXkc1sZGvsSVtIPKkJhi3N0NO5uaLBQmrGw=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.kuldeepsahu67.Mega_FilmessHD',
    appId: 'com.kuldeepsahu67.Mega_FilmessHD',
    title: 'Mega Filmes HD',
    summary: 'Receba em Seu smartphones Filmes Online do site mega Filmes com CONTEÚDOS',
    developer: 'Ocean Info',
    developerId: 'Ocean+Info',
    icon: '//lh3.googleusercontent.com/PsPD7YQf7iLCMmce2q5TzLvKPMadIpJLzc5kbsvwArApDylXKL3Mq_VCYI7UKMTNy-5Q=w340',
    score: 3,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.dotc.latin.ime.tap',
    appId: 'com.dotc.latin.ime.tap',
    title: 'Flash Keyboard Emoji',
    summary: 'emoji, emoticons e teclado inteligente',
    developer: 'Flashkeyboard Team',
    developerId: 'Flashkeyboard+Team',
    icon: '//lh3.googleusercontent.com/ud54Ibx-ZS9AXuqE6aTCYd21EgoiIGfyLqVjtKYmDr7MLOTGe9JkUv70oIbxLMG5zQMH=w340',
    score: 3,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.outfit7.talkingnewsfree',
    appId: 'com.outfit7.talkingnewsfree',
    title: 'Talking Tom & Ben News',
    summary: 'Tom e Ben estão ainda mais tagarelas e divertidos, como âncoras de telejornal!',
    developer: 'Outfit7',
    developerId: '5950758182267281572',
    icon: '//lh3.ggpht.com/wN2BSU5Oi7COw_lvOfKZ6VgYcmA3S_KbC1uoI6rnATQ71JbRB9Wp-POs-sUHEJWwqDs=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.pixel.art.coloring.color.number',
    appId: 'com.pixel.art.coloring.color.number',
    title: 'Livro para colorir com números grátis',
    summary: 'Livro de colorir para adultos e crianças. Pinte por números e relaxe! 💙💛💚',
    developer: 'Games For Rest',
    developerId: '6024334853127025460',
    icon: '//lh3.googleusercontent.com/HJ-u6Zwl8ZwbQUZN7Y2-bosFMDBVGhZNx-z9UOSe308HGY2_Qx8J7QBIp9b6zwYX3zae=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=riccisoftware.puxaassunto',
    appId: 'riccisoftware.puxaassunto',
    title: 'Puxa Assunto - Frases',
    summary: 'Vai passar vergonha ou vai Puxar Assunto?',
    developer: 'Ricci Software',
    developerId: 'Ricci+Software',
    icon: '//lh3.googleusercontent.com/8IHGeNhHdUH_uK3xXes2-PWc65MLkduJMsFpns_Tq6SQU_HybWfCGpGcC3TLvnOJkL_c=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.amektabat.colordrawcartoon.pawpatrol',
    appId: 'com.amektabat.colordrawcartoon.pawpatrol',
    title: 'How to color Paw Patrol coloring book for adult',
    summary: 'Este aplicativo contém uma abundância de páginas pronto para ser colorido, para os fãs de patrulha pata',
    developer: 'color and draw best cartoons in the world',
    developerId: 'color+and+draw+best+cartoons+in+the+world',
    icon: '//lh3.googleusercontent.com/mTLGZE1dUMNH5k65QsebLpNRp3Iu_YnFrDFnDOgrnOmaDJ8YykHRdn729QUsz1MqLA=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.cs.fieldglassesxx',
    appId: 'com.cs.fieldglassesxx',
    title: 'zoom binóculos xx',
    summary: 'Use binóculos para aproximar objetos remotos xx facilmente.',
    developer: 'jferconde',
    developerId: 'jferconde',
    icon: '//lh3.googleusercontent.com/SNIsC0CVUhDxNZgznC0XLm6qnLKkcD9ZhjNr07xVJVMCAkAo7P02B1lHbj_iiK_W_eqJ=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=smart.tv.wifi.remote.control.samcontrol',
    appId: 'smart.tv.wifi.remote.control.samcontrol',
    title: 'TV (Samsung) Remote Control | Smart & WiFi',
    summary: 'Controle remoto para TV Samsung. Por favor, leia a descrição como se conectar a TV.',
    developer: 'Backslash',
    developerId: 'Backslash',
    icon: '//lh3.googleusercontent.com/qxGWYRv_ggv_QL00TPOwggnNNXguQcrTQlL05Y4S7DxWZiQtVzOK5YDA3BBn4NuRFw=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.avarmmg.net.loudestairhorn',
    appId: 'com.avarmmg.net.loudestairhorn',
    title: 'Loudest Air Horn',
    summary: 'Se você quiser fazer barulho, torná-lo com esta aplicação buzina de ar',
    developer: 'Avar Apps',
    developerId: 'Avar+Apps',
    icon: '//lh3.googleusercontent.com/m4-c3WwGdYn98pVe21lduh1K552M71rHIrpA84tmyuOvaTD7HoRA0UOpGRrbFd93jw=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.outfit7.gingersbirthdayfree',
    appId: 'com.outfit7.gingersbirthdayfree',
    title: 'Talking Ginger 2',
    summary: 'É hora de um pouco de diversão de aniversário!',
    developer: 'Outfit7',
    developerId: '5950758182267281572',
    icon: '//lh3.googleusercontent.com/6Gxa9G8EQPFoFZf2OAtZnWdqSCuqJ7PowSQYSa6df_ucKcDLb1s0mSiUP3SiieL4Fw=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.ir.ticket',
    appId: 'com.ir.ticket',
    title: 'Ingresso Rápido',
    summary: 'A forma mais simples e segura de adquirir seus ingressos.',
    developer: 'Ingresso Rápido',
    developerId: 'Ingresso+R%C3%A1pido',
    icon: '//lh3.googleusercontent.com/_njPkmbj7fVibAtG9HNGIb0Zm_EvNmjH2thYaJ1DMuiQBtgc0PwTJpMZc5UaNfN9kX8=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.diariodeumvampiro.android',
    appId: 'com.diariodeumvampiro.android',
    title: 'Serie The Vampire Diaries',
    summary: 'Série Diario de um Vampiro Completa.',
    developer: 'D.B.R. Dev Mobile',
    developerId: 'D.B.R.+Dev+Mobile',
    icon: '//lh3.googleusercontent.com/ksKSVQZBkxAYe9F9y9-aclNccyb1fMT9gHqBYWbV9Kk9Cd2N1RdNaq2MYfZPl2vnTILz=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.lge.tv.remoteapps',
    appId: 'com.lge.tv.remoteapps',
    title: 'LG TV Remote',
    summary: 'Basta jogar o seu Smart TV com seu smartphone!',
    developer: 'LG Electronics, Inc.',
    developerId: '6033443741999759446',
    icon: '//lh6.ggpht.com/50NlVId21DICvWRCmAtJyjfCgKhEEaoJVDFijc6izVMzkRDF_28DbmBGGsNLZhrCTyc=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=mcpe.mods.modsforminecraft.lari',
    appId: 'mcpe.mods.modsforminecraft.lari',
    title: 'Mods for minecraft',
    summary: 'Only most popular mods for minecraft here!',
    developer: 'LariYuri&ShokoD',
    developerId: 'LariYuri%26ShokoD',
    icon: '//lh3.googleusercontent.com/9R5VvBN7u_wWfSTwD1jYvYM0eC5RDeMfGc-JMBVxgUICiaBTRSqjKkUEUaEJP-7D-UsS=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=br.com.band.guiatv',
    appId: 'br.com.band.guiatv',
    title: 'BAND',
    summary: 'BAND aplicativo oficial - TV ao Vivo, Segunda Tela e Vídeos.',
    developer: 'Band',
    developerId: 'Band',
    icon: '//lh3.ggpht.com/eIDMpb_7dLJ-7XJyKE5GEiP0UNzuRHcStHwLwZVXZtjnYjeJ48Qbc8N8cAKjqb8tK78=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.pop.popfilmes',
    appId: 'com.pop.popfilmes',
    title: 'MM Filmes HD',
    summary: 'Fique por dentro dos lançamentos de Filmes e Séries ao vivo.',
    developer: 'Pop My Cash',
    developerId: 'Pop+My+Cash',
    icon: '//lh3.googleusercontent.com/Eus0tMjPapSCpv3cMMGssW8NYThgJZgM4P1rRzcx3ftRruU1ZFTLP8ZhIRnxEm_R2po=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=br.mobilepx.felizdiadamulher',
    appId: 'br.mobilepx.felizdiadamulher',
    title: 'Feliz Dia da Mulher',
    summary: 'As melhores mensagens para homenagear as mulheres nessa data importante.',
    developer: 'MobilePX Pro',
    developerId: 'MobilePX+Pro',
    icon: '//lh3.googleusercontent.com/nIg7Dek-ZMvl-sQyM-l9qNNEnrQEFhI6xXwQrzhH84JQxf_989vTpapjaRRZvTRrR8g=w340',
    score: 3,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.watchever.studioplus',
    appId: 'com.watchever.studioplus',
    title: 'STUDIO+: Premium Short Series',
    summary: 'O primeiro app para as séries curta e premium',
    developer: 'STUDIO+ International',
    developerId: 'STUDIO%2B+International',
    icon: '//lh3.googleusercontent.com/n0Q6sSnetwQC0IuPj0vQI3vl9wh_uWSItmOYzyOy4s6palEOsAZ1hReBvrfjTvwtM-k=w340',
    score: 3,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=hu.tonuzaba.android',
    appId: 'hu.tonuzaba.android',
    title: 'Photo Warp',
    summary: 'Esse aplicativo divertido vai deixar você maravilhado!',
    developer: 'PWA STUDIO',
    developerId: '8916436038642286022',
    icon: '//lh3.googleusercontent.com/d7fHZcgjeHGSf9VIPK3Xz-uAjgt2OFasKpsTGOK5R8VlL4WwTolZYtGL3UndM7y6pCY=w340',
    score: 3,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=lioncash.lioncash',
    appId: 'lioncash.lioncash',
    title: 'Lioncash - Ganhar dinheiro',
    summary: 'Ganhar dinheiro com seu celular agora é fácil com a Lioncash!',
    developer: 'Lioncash',
    developerId: 'Lioncash',
    icon: '//lh3.googleusercontent.com/-9SHc6HFc6qm56KIQFXoHk9fwWU9fd_0xaO9OWaO_7mlguR8gZnbsYth2gBIjNBzvzOs=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.naver.vapp',
    appId: 'com.naver.vapp',
    title: 'V – Live Broadcasting  App',
    summary: 'Você pode assistir a transmissões ao vivo e vídeos exclusivos de celebridades favoritas',
    developer: 'NAVER Corp.',
    developerId: '6225315284672069550',
    icon: '//lh3.googleusercontent.com/cA8oOabrL1JMngJNYL71X7aEDKJeb4OjYXKMuk3t-gt3Z4Pr0gUSA9d6Pa0Zxk-JZhwE=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.mod.weapons.modteam',
    appId: 'com.mod.weapons.modteam',
    title: 'Guns & Weapons Mod for MCPE',
    summary: 'Armas e Armas Mod para MCPE',
    developer: 'Mod Emporium',
    developerId: 'Mod+Emporium',
    icon: '//lh3.googleusercontent.com/e_AZ8qx-dC3rEhr0tWTdE_OSA_ExxPCBUvCkRscyaJ379_0Z0A-FjO2-aBWKI6UbqK0=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.appcontent.nnone11',
    appId: 'com.appcontent.nnone11',
    title: 'Tv hd...vip',
    summary: 'o melhor app',
    developer: 'Tibax',
    developerId: 'Tibax',
    icon: '//lh3.googleusercontent.com/iXIAxC5E3ns2fi2z3u1baDVsK2HR0SJFiH1ENwMszg5o1gkY63-HxIuPD280v-sUOO8=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.SgyApps.multicraftcreative',
    appId: 'com.SgyApps.multicraftcreative',
    title: 'Crafting for Minecraft',
    summary: 'Crafting, forno, poções app guia para Minecraft!',
    developer: 'SGYapps',
    developerId: 'SGYapps',
    icon: '//lh3.googleusercontent.com/EwJ7ARw7Sdw5FJHOOz1hQZwk1H08IQjzmq4LWQTqCU1SKUdKCpRKwXiPnME4EK8LF5U=w340',
    score: 3,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.scee.psxandroid',
    appId: 'com.scee.psxandroid',
    title: 'PlayStation App',
    summary: 'CONTINUE NO JOGO',
    developer: 'PlayStation Mobile Inc.',
    developerId: '5810481673801929430',
    icon: '//lh3.googleusercontent.com/s7pAv2ne1q3xH3xfaISTliNiFHTV5tm_6WbtYmI_Xs8FcDv7GIjKlPSB8J9IYeYW5k8=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=videosluccasneto.rfm.com.videosluccasneto',
    appId: 'videosluccasneto.rfm.com.videosluccasneto',
    title: 'Videos do Luccas Neto',
    summary: 'Assista os últimos vídeos do Luccas Neto',
    developer: 'RODRIGO FRANCISCO DE MATTOS',
    developerId: 'RODRIGO+FRANCISCO+DE+MATTOS',
    icon: '//lh3.googleusercontent.com/wOg0tk6NIXF1dEHpA08bU-L6roI4Jd3oIbjpJT5XK9h3Kp5yKn4AKhaY6qTxDxMrgn8=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.dla.android',
    appId: 'com.dla.android',
    title: 'Claro video',
    summary: 'Claro video. O melhor entretenimento onde você quiser.',
    developer: 'CLARO',
    developerId: 'CLARO',
    icon: '//lh3.googleusercontent.com/FspHUl6AMlf8qPMx-ioPTpdexCXI8j3xsagbq4nlee9PXBdOzUJpLc3bfOQWjlckntE=w340',
    score: 3,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.inapp.jigsaw.puzzles.jigsaw1000',
    appId: 'com.inapp.jigsaw.puzzles.jigsaw1000',
    title: 'Jigsaw1000 - Jigsaw puzzles',
    summary: 'jogo de quebra-cabeça livre! Popular entre adultos e crianças! Dificuldade de 16-1000 peças',
    developer: 'incolor',
    developerId: 'incolor',
    icon: '//lh3.googleusercontent.com/usRjd1N61muR10YIlmWlO4-1Ivj7rD-sAzFyBcORPs4u_eVthpc6wA7bWqaeoVsOYBk=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.br.bebebebr',
    appId: 'com.br.bebebebr',
    title: 'BBB18 - Notícias, vídeos',
    summary: 'Fique por dentro do que acontece na casa mais vigiada do Brasil.',
    developer: 'GVD Softwares',
    developerId: 'GVD+Softwares',
    icon: '//lh3.googleusercontent.com/VWF3xnGGJdFZyTJho2yauBuWveXX6DL-v8IQni8rTHbjBwVOqUb03YxVBreVSN21O5c=w340',
    score: 3,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.nzn.baixaki',
    appId: 'com.nzn.baixaki',
    title: 'Baixaki',
    summary: 'Descubra os melhores apps e jogos com o Baixaki.',
    developer: 'NZN',
    developerId: '7301986430713509949',
    icon: '//lh4.ggpht.com/uhWqllATAtMCIUmfOROxMywTZrNbhuu3RYydSat7WFKHoZKCuZwKvDbYEc7de3QhmorQ=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=sg.bigo.gaming',
    appId: 'sg.bigo.gaming',
    title: 'Cube TV - comunidade global de Games ao vivo',
    summary: 'Plataforma líder de transmissão interativa para jogos.',
    developer: 'BIGO TECHNOLOGY PTE. LTD.',
    developerId: 'BIGO+TECHNOLOGY+PTE.+LTD.',
    icon: '//lh3.googleusercontent.com/3dS-llFVTShvltBsMsiBg3LuHa8n1kwb82UCublHJh_M_6iZCcRGXI0FDGRMkc8rius=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=br.com.escolhatecnologia.voztradutor',
    appId: 'br.com.escolhatecnologia.voztradutor',
    title: 'Voz da Mulher do Tradutor OFICIAL',
    summary: 'Envie mensagens para seus amigos com a voz do tradutor,  diversão garantida !!!',
    developer: 'Escolha Tecnologia',
    developerId: '5978392300521042263',
    icon: '//lh4.ggpht.com/Zuc3xQDzta9UaaFpC4Fakh0nBbuSAo5bQPVE-Ue4m2HSv4w7F9oJk-lCN44Gj4r3cLg=w340',
    score: 4,
    price: '0',
    free: true },
  { url: 'https://play.google.com/store/apps/details?id=com.lordofapps.sugartestprank',
    appId: 'com.lordofapps.sugartestprank',
    title: 'de açúcar no sangue Checker',
    summary: 'Verifique seu nível de açúcar no sangue com esta máquina de verificador açúcar',
    developer: 'Lord of Apps',
    developerId: 'Lord+of+Apps',
    icon: '//lh3.googleusercontent.com/ym6jMqCiRwKp65-hyXHA7wgN4IHLcWOCCfaspvf7IFjZJOSyatBMd9CXYf5ioLmeJdCb=w340',
    score: 3,
    price: '0',
    free: true } ]
arra = []


for (var r = 0; r < arr.length; r++) {
  if((arr[r]['score']) <= 2) arra.push(arr[r])
}

console.log(arra);
console.log("###### END ######");
